<?xml version="1.0" encoding="utf-8"?><Database Name="db96bccf3def02407592bda59e000bc2b9" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=96bccf3d-ef02-4075-92bd-a59e000bc2b9.sqlserver.sequelizer.com;Initial Catalog=db96bccf3def02407592bda59e000bc2b9;Persist Security Info=True;User ID=nyndondnthbiaoze" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db96bccf3def02407592bda59e000bc2b9ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Views" Member="Views">
    <Type Name="View">
      <Column Name="VID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SegID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Segments" Member="Segments">
    <Type Name="Segment">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SegmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BearingArray" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Polyline" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SegmentName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="latlng" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrivateSeg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopWeather" Member="TopWeathers">
    <Type Name="TopWeather">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SegID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Windspeed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stars" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="latlng" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="epoch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TS_pretty" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SegName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Polyline" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StravaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Credits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreditsWait" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activities" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Segments" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="latlng" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logdata" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstLogin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LastRefresh" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PaymentID" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>